# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AC_REPOSITORY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t ${{ secrets.AC_REPOSITORY_URL }}/calculator:${{ github.sha }}
        docker push ${{ secrets.AC_REPOSITORY_URL }}/calculator:${{ github.sha }}     

    #- uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: 'myapp'
    #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #    images: 'AC_REPOSITORY_URL/myapp:${{ github.sha }}'